// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgqPNR8XGfMhKm611UDZUMfqxA8M8cFK0',
    appId: '1:918126420439:web:dab2e42e6785e1b667eb92',
    messagingSenderId: '918126420439',
    projectId: 'flutter-chat-app-255f1',
    authDomain: 'flutter-chat-app-255f1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-255f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5shedCjiok1hrswEuSdIWPTrm9XtC2yg',
    appId: '1:918126420439:android:5fa94077d48f6f5467eb92',
    messagingSenderId: '918126420439',
    projectId: 'flutter-chat-app-255f1',
    storageBucket: 'flutter-chat-app-255f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8yc7xG4DytvRDd_Xj6AmWSeyQVQwPQMw',
    appId: '1:918126420439:ios:4415b651017aa7b867eb92',
    messagingSenderId: '918126420439',
    projectId: 'flutter-chat-app-255f1',
    storageBucket: 'flutter-chat-app-255f1.firebasestorage.app',
    iosBundleId: 'com.baniyaprasannata.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8yc7xG4DytvRDd_Xj6AmWSeyQVQwPQMw',
    appId: '1:918126420439:ios:4415b651017aa7b867eb92',
    messagingSenderId: '918126420439',
    projectId: 'flutter-chat-app-255f1',
    storageBucket: 'flutter-chat-app-255f1.firebasestorage.app',
    iosBundleId: 'com.baniyaprasannata.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgqPNR8XGfMhKm611UDZUMfqxA8M8cFK0',
    appId: '1:918126420439:web:a785bd38979957d667eb92',
    messagingSenderId: '918126420439',
    projectId: 'flutter-chat-app-255f1',
    authDomain: 'flutter-chat-app-255f1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-255f1.firebasestorage.app',
  );
}
